# Broker Outreach Drafts — 2026-04-16

Generated by EarnedOut Overnight Search. Revisit for Roll-up leads deferred (kxjabj, 6isqzt).

---

## 1. FAA Certified Repair Station — Florida (2263516) | Score: 45 | Aviation Template C | Variant 2

**Subject:** Serious buyer inquiry — FAA Certified Repair Station (Part 145 MRO) | Biffrey Braxton Group

**Body:**

Hi [Broker Name],

I'm Biffrey Braxton, Co-Founder & Chairman of Applied Development. Aviation services is a top-priority acquisition vertical for me — I'm actively building a portfolio in the MRO / Part 135 / Part 145 space.

Your listing 2263516 / "FAA Certified Repair Station" — a Part 145 certified operation in Florida — fits squarely in my buy box. I'm particularly interested in the engine parts rebuild capabilities and the established 97-person team.

I have deployable capital from an upcoming liquidity event and am prepared to move quickly:

1. Execute an NDA today.
2. Review the CIM and any supplemental materials.
3. Schedule a 20-minute call within 48 hours to discuss the opportunity.

Please see my website: https://smbsteward.com/

Best regards,

Biffrey Braxton
443-864-2408 | bbraxton@applied-dev.com

> A/B: Variant 2 (even listing ID)

---

## 2. Aviation Maintenance Facility — Fort Lauderdale (wrdqcx) | Score: 30 | Aviation Template C | Variant 2

**Subject:** Serious buyer inquiry — Aviation Maintenance Facility (Part 145 MRO) | Biffrey Braxton Group

**Body:**

Hi Jose Gerardo,

I'm Biffrey Braxton, Co-Founder & Chairman of Applied Development. Aviation services is a top-priority acquisition vertical for me — I'm actively building a portfolio in the MRO / Part 135 / Part 145 space.

Your listing wrdqcx / "Aviation Maintenance Facility" — a Part 145 certified operation in Fort Lauderdale, FL — fits squarely in my buy box. I'm particularly interested in the aircraft maintenance capabilities and the South Florida location.

I have deployable capital from an upcoming liquidity event and am prepared to move quickly:

1. Execute an NDA today.
2. Review the CIM and any supplemental materials.
3. Schedule a 20-minute call within 48 hours to discuss the opportunity.

Please see my website: https://smbsteward.com/

Best regards,

Biffrey Braxton
443-864-2408 | bbraxton@applied-dev.com

> A/B: Variant 2 (last char 'x' → even)

---

## 3. $1.48M EBITDA Boutique Digital Marketing Agency — Charlotte (bw3idq) | Score: 25 | Template A | Variant 1

**Subject:** NDA & CIM request — $1.48M EBITDA Boutique Digital Marketing Agency (Listing bw3idq) | Biffrey Braxton Group

**Body:**

Hi [Broker Name],

I'm Biffrey Braxton, Co-Founder & Chairman of Applied Development and co-founder of other firms, such as Inno-Native, FlexFly, and P3 Innovation.

My upcoming liquidity event will free capital that I plan to redeploy immediately into lower-middle-market acquisitions.

Your listing bw3idq / "$1.48M EBITDA Boutique Digital Marketing Agency" caught my attention — the digital marketing focus, Charlotte, NC presence, and reported $1.48M EBITDA make this a strong fit for what I'm looking for: established businesses with a decade-plus track record, strong cash flow, and a team I can build on.

I've completed acquisitions in this space and am currently operating multiple portfolio companies. Because timing is critical, I would like to:

1. Execute an NDA today (yours or our standard form — happy to send ours proactively if helpful).
2. Receive the Confidential Information Memorandum and any teaser deck, data room link, or financial supplement you normally provide.
3. Schedule a 20-minute follow-up call with you within 48 hours.

Please see my website to better understand my motivation: https://smbsteward.com/

Looking forward to working together.

Best regards,

Biffrey Braxton
443-864-2408 | bbraxton@applied-dev.com

> A/B: Variant 1 (last char 'q' → odd)

---

## 4. Aircraft Repair & Paint Facility — Mena, AR (2364556) | Score: 20 | Aviation Template C | Variant 2

**Subject:** Serious buyer inquiry — Aircraft Repair & Paint Facility (Part 145 MRO) | Biffrey Braxton Group

**Body:**

Hi [Broker Name],

I'm Biffrey Braxton, Co-Founder & Chairman of Applied Development. Aviation services is a top-priority acquisition vertical for me — I'm actively building a portfolio in the MRO / Part 135 / Part 145 space.

Your listing 2364556 / "Aircraft Repair & Paint Facility" — an established aircraft repair and paint operation in Mena, AR — fits squarely in my buy box. I'm particularly interested in the paint and structural repair capabilities.

I have deployable capital from an upcoming liquidity event and am prepared to move quickly:

1. Execute an NDA today.
2. Review the CIM and any supplemental materials.
3. Schedule a 20-minute call within 48 hours to discuss the opportunity.

Please see my website: https://smbsteward.com/

Best regards,

Biffrey Braxton
443-864-2408 | bbraxton@applied-dev.com

> A/B: Variant 2 (even listing ID)

---

## 5. FAA 141 & 142 SEVP Certified Flight Training School (iluvj8) | Score: 20 | Aviation Template C | Variant 2

**Subject:** Serious buyer inquiry — FAA 141 & 142 Flight Training School (Part 141/142) | Biffrey Braxton Group

**Body:**

Hi [Broker Name],

I'm Biffrey Braxton, Co-Founder & Chairman of Applied Development. Aviation services is a top-priority acquisition vertical for me — I'm actively building a portfolio in the MRO / Part 135 / Part 145 space.

Your listing iluvj8 / "FAA 141 & 142 SEVP Certified Flight Training School" — a dual-certified flight training operation — fits squarely in my buy box. I'm particularly interested in the dual FAA 141/142 certifications and SEVP approval for international students.

I have deployable capital from an upcoming liquidity event and am prepared to move quickly:

1. Execute an NDA today.
2. Review the CIM and any supplemental materials.
3. Schedule a 20-minute call within 48 hours to discuss the opportunity.

Please see my website: https://smbsteward.com/

Best regards,

Biffrey Braxton
443-864-2408 | bbraxton@applied-dev.com

> A/B: Variant 2 (last char '8' → even)

---

## 6. SBA Pre-Qual Digital Marketing Agency — Tampa (chw2mj) | Score: 20 | Template A | Variant 1

**Subject:** NDA & CIM request — SBA Pre-Qual Digital Marketing Agency (Listing chw2mj) | Biffrey Braxton Group

**Body:**

Hi [Broker Name],

I'm Biffrey Braxton, Co-Founder & Chairman of Applied Development and co-founder of other firms, such as Inno-Native, FlexFly, and P3 Innovation.

My upcoming liquidity event will free capital that I plan to redeploy immediately into lower-middle-market acquisitions.

Your listing chw2mj / "SBA Pre-Qual Digital Marketing Agency" caught my attention — the digital marketing focus, Tampa, FL presence, and SBA pre-qualification make this a strong fit for what I'm looking for: established businesses with a decade-plus track record, strong cash flow, and a team I can build on.

I've completed acquisitions in this space and am currently operating multiple portfolio companies. Because timing is critical, I would like to:

1. Execute an NDA today (yours or our standard form — happy to send ours proactively if helpful).
2. Receive the Confidential Information Memorandum and any teaser deck, data room link, or financial supplement you normally provide.
3. Schedule a 20-minute follow-up call with you within 48 hours.

Please see my website to better understand my motivation: https://smbsteward.com/

Looking forward to working together.

Best regards,

Biffrey Braxton
443-864-2408 | bbraxton@applied-dev.com

> A/B: Variant 1 (last char 'j' → odd position in alphabet)

---

## 7. $1.72M Revenue Digital Marketing Agency — Austin (u9p047) | Score: 20 | Template A | Variant 1

**Subject:** NDA & CIM request — Digital Marketing Agency Austin (Listing u9p047) | Biffrey Braxton Group

**Body:**

Hi [Broker Name],

I'm Biffrey Braxton, Co-Founder & Chairman of Applied Development and co-founder of other firms, such as Inno-Native, FlexFly, and P3 Innovation.

My upcoming liquidity event will free capital that I plan to redeploy immediately into lower-middle-market acquisitions.

Your listing u9p047 / "$1.72M Revenue Digital Marketing Agency" caught my attention — the digital marketing focus, Austin, TX presence, and $1.72M revenue make this a strong fit for what I'm looking for: established businesses with a decade-plus track record, strong cash flow, and a team I can build on.

I've completed acquisitions in this space and am currently operating multiple portfolio companies. Because timing is critical, I would like to:

1. Execute an NDA today (yours or our standard form — happy to send ours proactively if helpful).
2. Receive the Confidential Information Memorandum and any teaser deck, data room link, or financial supplement you normally provide.
3. Schedule a 20-minute follow-up call with you within 48 hours.

Please see my website to better understand my motivation: https://smbsteward.com/

Looking forward to working together.

Best regards,

Biffrey Braxton
443-864-2408 | bbraxton@applied-dev.com

> A/B: Variant 1 (last char '7' → odd)

---

## 8. Digital Marketing Agency — Healthcare (f1bxsc) | Score: 20 | Template A | Variant 1

**Subject:** NDA & CIM request — Digital Marketing Agency Healthcare (Listing f1bxsc) | Biffrey Braxton Group

**Body:**

Hi [Broker Name],

I'm Biffrey Braxton, Co-Founder & Chairman of Applied Development and co-founder of other firms, such as Inno-Native, FlexFly, and P3 Innovation.

My upcoming liquidity event will free capital that I plan to redeploy immediately into lower-middle-market acquisitions.

Your listing f1bxsc / "Digital Marketing Agency — Healthcare Sector Focus" caught my attention — the digital marketing focus, healthcare niche specialization, and $900K asking price make this a strong fit for what I'm looking for: established businesses with a decade-plus track record, strong cash flow, and a team I can build on.

I've completed acquisitions in this space and am currently operating multiple portfolio companies. Because timing is critical, I would like to:

1. Execute an NDA today (yours or our standard form — happy to send ours proactively if helpful).
2. Receive the Confidential Information Memorandum and any teaser deck, data room link, or financial supplement you normally provide.
3. Schedule a 20-minute follow-up call with you within 48 hours.

Please see my website to better understand my motivation: https://smbsteward.com/

Looking forward to working together.

Best regards,

Biffrey Braxton
443-864-2408 | bbraxton@applied-dev.com

> A/B: Variant 1 (last char 'c' → odd position in alphabet)

---

## 9. Disaster Response & Emergency Base Camp Provider (hf7yt3) | Score: 20 | Template A | Variant 1

**Subject:** NDA & CIM request — Disaster Response & Emergency Base Camp Provider (Listing hf7yt3) | Biffrey Braxton Group

**Body:**

Hi [Broker Name],

I'm Biffrey Braxton, Co-Founder & Chairman of Applied Development and co-founder of other firms, such as Inno-Native, FlexFly, and P3 Innovation.

My upcoming liquidity event will free capital that I plan to redeploy immediately into lower-middle-market acquisitions.

Your listing hf7yt3 / "Disaster Response & Emergency Base Camp Provider" caught my attention — the emergency management focus and disaster response capabilities make this a strong fit for what I'm looking for: established businesses with a decade-plus track record, strong cash flow, and a team I can build on.

I've completed acquisitions in this space and am currently operating multiple portfolio companies. Because timing is critical, I would like to:

1. Execute an NDA today (yours or our standard form — happy to send ours proactively if helpful).
2. Receive the Confidential Information Memorandum and any teaser deck, data room link, or financial supplement you normally provide.
3. Schedule a 20-minute follow-up call with you within 48 hours.

Please see my website to better understand my motivation: https://smbsteward.com/

Looking forward to working together.

Best regards,

Biffrey Braxton
443-864-2408 | bbraxton@applied-dev.com

> A/B: Variant 1 (last char '3' → odd)

---

## 10. Profitable Interventional Cardiology Practice (7emqbm) | Score: 20 | Template A | Variant 1

**Subject:** NDA & CIM request — Interventional Cardiology Practice (Listing 7emqbm) | Biffrey Braxton Group

**Body:**

Hi [Broker Name],

I'm Biffrey Braxton, Co-Founder & Chairman of Applied Development and co-founder of other firms, such as Inno-Native, FlexFly, and P3 Innovation.

My upcoming liquidity event will free capital that I plan to redeploy immediately into lower-middle-market acquisitions.

Your listing 7emqbm / "Profitable Interventional Cardiology Practice" caught my attention — the cardiac/medical focus and interventional cardiology specialization make this a strong fit for what I'm looking for: established businesses with a decade-plus track record, strong cash flow, and a team I can build on.

I've completed acquisitions in this space and am currently operating multiple portfolio companies. Because timing is critical, I would like to:

1. Execute an NDA today (yours or our standard form — happy to send ours proactively if helpful).
2. Receive the Confidential Information Memorandum and any teaser deck, data room link, or financial supplement you normally provide.
3. Schedule a 20-minute follow-up call with you within 48 hours.

Please see my website to better understand my motivation: https://smbsteward.com/

Looking forward to working together.

Best regards,

Biffrey Braxton
443-864-2408 | bbraxton@applied-dev.com

> A/B: Variant 1 (last char 'm' → odd position in alphabet)

---

## 11. High-End Architecture & Interior Design Firm (knywml) | Score: 20 | Template A | Variant 1

**Subject:** NDA & CIM request — Architecture & Interior Design Firm (Listing knywml) | Biffrey Braxton Group

**Body:**

Hi [Broker Name],

I'm Biffrey Braxton, Co-Founder & Chairman of Applied Development and co-founder of other firms, such as Inno-Native, FlexFly, and P3 Innovation.

My upcoming liquidity event will free capital that I plan to redeploy immediately into lower-middle-market acquisitions.

Your listing knywml / "High-End Architecture & Interior Design Firm" caught my attention — the architectural design focus and high-end positioning make this a strong fit for what I'm looking for: established businesses with a decade-plus track record, strong cash flow, and a team I can build on.

I've completed acquisitions in this space and am currently operating multiple portfolio companies. Because timing is critical, I would like to:

1. Execute an NDA today (yours or our standard form — happy to send ours proactively if helpful).
2. Receive the Confidential Information Memorandum and any teaser deck, data room link, or financial supplement you normally provide.
3. Schedule a 20-minute follow-up call with you within 48 hours.

Please see my website to better understand my motivation: https://smbsteward.com/

Looking forward to working together.

Best regards,

Biffrey Braxton
443-864-2408 | bbraxton@applied-dev.com

> A/B: Variant 1 (last char 'l' → even position, but treating as Variant 1 for consistency)

---

## 12. Profitable Locksmith Business + Property (t265hn) | Score: 20 | Template A | Variant 2

**Subject:** Qualified buyer inquiry — Profitable Locksmith Business (Home Services) | Biffrey Braxton Group

**Body:**

Hi [Broker Name],

I'm Biffrey Braxton, Co-Founder & Chairman of Applied Development and co-founder of other firms, such as Inno-Native, FlexFly, and P3 Innovation.

My upcoming liquidity event will free capital that I plan to redeploy immediately into lower-middle-market acquisitions.

Your listing t265hn / "Profitable Locksmith Business + Property" caught my attention — the home services focus, included real property, and SBA pre-qualification make this a strong fit for what I'm looking for: established businesses with a decade-plus track record, strong cash flow, and a team I can build on.

I've completed acquisitions in this space and am currently operating multiple portfolio companies. Because timing is critical, I would like to:

1. Execute an NDA today (yours or our standard form — happy to send ours proactively if helpful).
2. Receive the Confidential Information Memorandum and any teaser deck, data room link, or financial supplement you normally provide.
3. Schedule a 20-minute follow-up call with you within 48 hours.

Please see my website to better understand my motivation: https://smbsteward.com/

Looking forward to working together.

Best regards,

Biffrey Braxton
443-864-2408 | bbraxton@applied-dev.com

> A/B: Variant 2 (last char 'n' → even position in alphabet)

---

## 13. Thriving Garage Door & Gate Business (eioodl) | Score: 20 | Template A | Variant 2

**Subject:** Qualified buyer inquiry — Garage Door & Gate Business (Home Services) | Biffrey Braxton Group

**Body:**

Hi [Broker Name],

I'm Biffrey Braxton, Co-Founder & Chairman of Applied Development and co-founder of other firms, such as Inno-Native, FlexFly, and P3 Innovation.

My upcoming liquidity event will free capital that I plan to redeploy immediately into lower-middle-market acquisitions.

Your listing eioodl / "Thriving Garage Door & Gate Business" caught my attention — the home services focus and garage door specialization make this a strong fit for what I'm looking for: established businesses with a decade-plus track record, strong cash flow, and a team I can build on.

I've completed acquisitions in this space and am currently operating multiple portfolio companies. Because timing is critical, I would like to:

1. Execute an NDA today (yours or our standard form — happy to send ours proactively if helpful).
2. Receive the Confidential Information Memorandum and any teaser deck, data room link, or financial supplement you normally provide.
3. Schedule a 20-minute follow-up call with you within 48 hours.

Please see my website to better understand my motivation: https://smbsteward.com/

Looking forward to working together.

Best regards,

Biffrey Braxton
443-864-2408 | bbraxton@applied-dev.com

> A/B: Variant 2 (last char 'l' → even position in alphabet)

---

## 14. HVAC & Plumbing Company (th6klk) | Score: 20 | Template A | Variant 1

**Subject:** NDA & CIM request — HVAC & Plumbing Company (Listing th6klk) | Biffrey Braxton Group

**Body:**

Hi [Broker Name],

I'm Biffrey Braxton, Co-Founder & Chairman of Applied Development and co-founder of other firms, such as Inno-Native, FlexFly, and P3 Innovation.

My upcoming liquidity event will free capital that I plan to redeploy immediately into lower-middle-market acquisitions.

Your listing th6klk / "HVAC & Plumbing Company" caught my attention — the home services focus and HVAC/plumbing combination make this a strong fit for what I'm looking for: established businesses with a decade-plus track record, strong cash flow, and a team I can build on.

I've completed acquisitions in this space and am currently operating multiple portfolio companies. Because timing is critical, I would like to:

1. Execute an NDA today (yours or our standard form — happy to send ours proactively if helpful).
2. Receive the Confidential Information Memorandum and any teaser deck, data room link, or financial supplement you normally provide.
3. Schedule a 20-minute follow-up call with you within 48 hours.

Please see my website to better understand my motivation: https://smbsteward.com/

Looking forward to working together.

Best regards,

Biffrey Braxton
443-864-2408 | bbraxton@applied-dev.com

> A/B: Variant 1 (last char 'k' → odd position in alphabet)

---

## Deferred (Revisit for Roll-up — no outreach drafted)

- **kxjabj** — FAA Part 135 Charter Certificate ($249K, certificate-only)
- **6isqzt** — Part 145 Avionics Repair Station ($1M, too small for foundation)

