> **⚙️ BUILD-LOOP s10 END-TO-END DRY-RUN ARTIFACT** — This report was
> regenerated by the off-market-search build loop, stage **s10 (assembly &
> end-to-end dry run) IMPLEMENT** (iter 31), to resolve **BLOCKING-s10-1**. It
> is a test artifact produced by driving the Class-2 (SBIC) `LeadPacket` at
> `lead-packet.json` through the unmodified `prospect-evaluation` skill in
> **SBIC mode**, scored **strictly from that packet** — no value appears here
> that is not in `lead-packet.json`. Not a live deal recommendation.

# 1st Source Capital Corporation — Prospect Evaluation

**Prepared for:** Biffrey Braxton / EarnedOut
**Report date:** 2026-05-22
**Prepared by:** Claude (Prospect Evaluation skill)
**Lead source:** Off-market search — SBA SBIC directory (government open data)
**Evaluation mode:** **SBIC** (rule 13) — license good-standing is the sole hard gate; the 0–100 score below is **informational only**

---

## Buy Box Screening

> **SBIC mode.** For an SBIC GP / management-company acquisition the standard
> six Buy Box checks are **reported but non-gating**. The **sole hard gate** is
> the SBIC license being **active and in good standing** — see the SBIC License
> Gate row. The 0–100 lead score is **informational only**.

| # | Criterion | Status | Evidence |
|---|-----------|:------:|----------|
| 1 | ≥ 10 full-time employees | ⚠️ | SBIC GP/management entity's FTE headcount not disclosed in the `LeadPacket`. Insufficient data. |
| 2 | EBITDA $1M–$4M / year | ⚠️ | No standalone P&L for the SBIC management entity. `sbic_gp_economics` (fund size $2.85M, avg investment $283,740) is fund-level informational data, **not** GP EBITDA. Insufficient data — not a ❌. |
| 3 | 10+ years in business | ⚠️ | **Insufficient data — not awarded.** The `LeadPacket` sets `formation_date` and `years_in_business` to `null` and lists "formation date" in `enrichment_gaps`. SBIC fund vintage (1983) is informational fund-level data, not the company's formation date — a gap stays a gap. Not a ❌. |
| 4 | 3+ yrs YoY revenue & profit growth | ⚠️ | No standalone SBIC-entity revenue/profit series disclosed. Insufficient data. |
| 5 | Asking price ≤ 4.0x EBITDA | ⚠️ | **Off-market target — not for sale, no asking price.** This is the expected state for an off-market candidate, **not an error**. Cannot evaluate a multiple without an ask. Insufficient data — not a ❌. |
| 6 | DSCR > 1.4 *(informational only)* | ⚠️ | No deal financing structure exists (off-market, no ask). Not computable. |

**SBIC License Gate (the sole hard criterion):** ✅ **PASS** — `sbic_license_status: Good Standing`. The SBA SBIC directory does not publish a standing flag; s5 enrichment's good-standing cross-check resolved the license as active and in good standing. Per `scoring_integration.md` §4: `Good Standing` → `buybox_gate: pass`.

**Overall Buy Box:** **CONDITIONAL** — In SBIC mode the only hard gate (license good standing) **PASSES**. All six standard checks are ⚠️ "insufficient data" because this is an off-market, not-for-sale target with no disclosed standalone GP financials and an unresolved formation date — none of these are deal-killers in SBIC mode, and none caused the run to abort.

**Lead Score:** **20 / 100** *(informational only — see note below)*

> **Score is informational.** Per `prospect-evaluation` rule 13 and
> `scoring_integration.md` §2, the 0–100 score does **not** gate an SBIC
> acquisition. The score is low because off-market enrichment legitimately
> leaves the standalone GP's EBITDA, FTE, growth, concentration, owner
> dependence, formation date, and (by definition) the valuation multiple
> **undisclosed** — each scores 0 as **"insufficient data — not awarded"**,
> which is *not* a negative judgment. The acquisition decision rests on the
> license gate (PASS) plus SBA change-of-control approval, not on this number.

---

## ⚠️ SBIC Closing Condition — SBA Prior Approval of Change of Control

**Acquiring a licensed SBIC requires SBA prior approval of the change of control.** Any transaction that transfers control of 1st Source Capital Corporation (the entity holding the SBA SBIC license) cannot close until the U.S. Small Business Administration has approved the change of control. This is a mandatory regulatory closing condition on every SBIC acquisition and must be built into the deal timeline and the purchase agreement (SBA approval as a condition precedent to closing). Source: off-market `LeadPacket` government fact; SBA SBIC program rules (13 CFR Part 107).

---

## Scorecard (26 fields)

| # | Field | Value | Source |
|---|-------|-------|--------|
| 1 | Business Name | 1st Source Capital Corporation | Off-market LeadPacket (SBA SBIC directory) |
| 2 | Lead Source | Off-market search — SBA SBIC directory (government open data) | Off-market LeadPacket |
| 3 | Years in business | Not disclosed — `formation_date` / `years_in_business` are `null` (enrichment gap) | Off-market LeadPacket |
| 4 | Value of real estate owned | Not disclosed | — |
| 5 | Value of FF&E | Not disclosed | — |
| 6 | Full-time employees | Not disclosed (SBIC GP entity) — needs follow-up | Enrichment gap |
| 7 | Part-time employees | Not disclosed | — |
| 8 | Contractors / 1099 | Not disclosed | — |
| 9 | Business address | South Bend, IN (city/state only — street address not in LeadPacket) | Off-market LeadPacket |
| 10 | Revenue 2022 | Not disclosed (no standalone SBIC-entity P&L) | — |
| 11 | Revenue 2023 | Not disclosed | — |
| 12 | Revenue 2024 | Not disclosed | — |
| 13 | Revenue 2025 | Not disclosed | — |
| 14 | Net / free cash flow 2022 | Not disclosed | — |
| 15 | Net / free cash flow 2023 | Not disclosed | — |
| 16 | Net / free cash flow 2024 | Not disclosed | — |
| 17 | Net / free cash flow 2025 | Not disclosed | — |
| 18 | Asking price | Not for sale — no asking price (off-market target) | Off-market LeadPacket |
| 19 | % revenue growth YoY | Not computable — no revenue series | — |
| 20 | Yearly revenue retention | Not disclosed | — |
| 21 | EBITDA margin | Not computable — EBITDA & revenue not disclosed | — |
| 22 | Customer LTV | Not disclosed (left blank per skill rule 3) | — |
| 23 | Customer CAC | Not disclosed (left blank per skill rule 3) | — |
| 24 | Client concentration (largest %) | Not disclosed | — |
| 25 | Link to 2024 financials + YTD | None — no data room (off-market) | — |
| 26 | **Lead Score** | **20 / 100** *(informational only — SBIC mode)* | computed |

> **Informational fund-level data (NOT mapped to any Buy Box financial criterion).** SBIC `sbic_gp_economics`: fund vintage 1983; fund size $2,850,000; average investment $283,740; strategy "Direct Lending"; **not currently making new investments**. Per `scoring_integration.md` §3.1 these are fund-level descriptors of the SBIC vehicle, not the GP/management entity's audited P&L or formation date — they were deliberately **not** mapped onto the EBITDA, revenue, valuation, or years-in-business lines.

---

## Lead Score Breakdown

| Item | Awarded | Max | Justification |
|------|:-------:|:---:|---------------|
| Industry match | 20 | 20 | SBIC GP / management company is an explicitly supported standalone target type (`prospect-evaluation` rule 13). Clean match. |
| EBITDA tier (non-cumulative) | 0 | 15 | **Insufficient data — not awarded.** No standalone P&L for the SBIC management entity. Fund size ($2.85M) is informational fund-level data, not GP EBITDA — never mapped onto this line. Not a judgment that EBITDA is low. |
| Years in business ≥10 | 0 | 10 | **Insufficient data — not awarded.** The `LeadPacket` sets `formation_date` and `years_in_business` to `null` and lists "formation date" in `enrichment_gaps`. SBIC fund vintage (1983) is informational fund-level data per `scoring_integration.md` §3.1, not the company formation date — a gap stays a gap (§3, lines 91-92, 99). |
| 3 yrs consistent rev + profit growth | 0 | 10 | **Insufficient data — not awarded.** No standalone revenue/profit series disclosed for the SBIC entity. |
| Recurring revenue | 0 | 10 | **Insufficient data — not awarded.** SBIC GP economics (management fees / interest income) not disclosed at the entity level; revenue mix cannot be confirmed. |
| Customer concentration <20% | 0 | 5 | **Insufficient data — not awarded.** Portfolio / LP concentration not disclosed. |
| Employees ≥10 | 0 | 10 | **Insufficient data — not awarded.** SBIC GP/management entity headcount not disclosed in the `LeadPacket`. |
| Valuation multiple | 0 | 15 | **Insufficient data — not awarded.** Off-market target — **no asking price exists**. Per `scoring_integration.md` §3.2 the valuation line scores 0 "insufficient data — not awarded"; it is **not a ❌**, the run did **not** abort, and the candidate was **not** dropped. |
| Low owner dependence | 0 | 5 | **Insufficient data — not awarded.** GP managing principal not yet identified (directory POC is investor relations, not the deal principal). |
| **Total** | **20** | **100** | Informational only — does not gate the SBIC decision. |

> **Math check:** 20 + 0 + 0 + 0 + 0 + 0 + 0 + 0 + 0 = **20**. Header (20) and per-line total (20) agree.
>
> **Why the score is low — and why that is expected.** Eight of the nine rubric lines score 0 as **"insufficient data — not awarded"**, not as failures. This is the designed behavior for an off-market candidate: the SBA SBIC directory publishes fund-level descriptors, not the GP entity's audited financials, headcount, formation date, or ownership detail, and an off-market target has no asking price. In SBIC mode the decision rests on the **license good-standing gate (PASS)** plus the **SBA change-of-control approval** condition — not on this number.

---

## 1. Executive Summary

- **Company overview:** 1st Source Capital Corporation is an SBA-licensed Small Business Investment Company (SBIC) located in South Bend, Indiana. The off-market `LeadPacket` records an SBIC fund vintage of 1983, a $2.85M fund size, a $283,740 average investment, and a direct-lending strategy; per the SBIC directory it is **not currently making new investments**. The company's formation/incorporation date and ownership structure are **not resolved** in the `LeadPacket` (enrichment gaps).
- **Financial highlights:** The SBIC management entity's standalone financials (revenue, EBITDA, margins, growth) are **not disclosed**. The only quantitative data in the `LeadPacket` is fund-level: $2.85M fund size, $283,740 average investment, direct-lending strategy — informational descriptors of the SBIC vehicle, not the GP entity's audited P&L.
- **Buy Box screening summary:** **CONDITIONAL** — SBIC mode. The sole hard gate (SBIC license active and in good standing) **PASSES**. All six standard Buy Box checks are ⚠️ "insufficient data" because this is an off-market, not-for-sale target with no disclosed standalone GP financials and an unresolved formation date.
- **Why pursue (or why not):**
  - **For:** A genuine SBA-licensed SBIC in good standing — the licensed SBIC charter itself is the strategic asset, and licenses are scarce and not freely transferable.
  - **Caution:** The SBIC is **not for sale** — there is no indication the owner is a willing seller. The ownership structure is not disclosed in the `LeadPacket`; whether an acquisition would be a clean buyout or a carve-out is an open enrichment question.
  - **Hard condition:** Any change of control requires **SBA prior approval** before closing.
  - **Score caveat:** The 20/100 lead score is **informational only** and reflects off-market data gaps, not a quality judgment.

---

## 2. Company Overview

- **Background and history:** 1st Source Capital Corporation is an SBA-licensed Small Business Investment Company (SBIC) located in South Bend, Indiana. The `LeadPacket` records an SBIC fund vintage of 1983 and a direct-lending strategy. The company's formation/incorporation date is **not disclosed** in the `LeadPacket` and is flagged as an enrichment gap — the fund vintage (1983) is the SBIC vehicle's vintage year, not a verified company formation date, and was not used to derive years-in-business.
- **Ownership structure:** **Not disclosed** in the `LeadPacket` — an open enrichment gap. Whether the SBIC is independently held or a subsidiary of a larger entity, and therefore whether an acquisition would be a direct buyout or a carve-out, could not be determined from the packet.
- **Key milestones and timeline:**
  - 1983 — SBIC fund vintage recorded in the `LeadPacket` (the earliest dated fact in the packet; the company's formation date itself is an enrichment gap).
  - 2026-05 — SBA SBIC directory lists it as a licensed SBIC in good standing, **not currently making new investments**.
- **Organizational structure and leadership:** The SBIC entity's standalone management team / managing principal is **not disclosed** by the SBA directory — the only published point of contact is investor relations (Ryan Fenstermaker), not the deal principal. Identifying the GP managing principal is an open enrichment gap.

---

## 3. Principals & Leadership Team

### Ryan Fenstermaker — Investor Relations
- **Role:** Directory / investor-relations point of contact. **Note:** this is *not* confirmed to be the SBIC's managing deal principal — it is the published IR contact. The actual GP managing principal is an open enrichment gap.
- **Professional background:** Not researched (IR contact, not a deal principal).
- **Contact:**
  - Email: fenstermakerr@1stsource.com
  - Phone: 574-235-2180
  - LinkedIn: not researched
  - Office: South Bend, IN

### GP Managing Principal — NOT IDENTIFIED (open gap)
- The individual(s) actually running the SBIC's investment decisions are **not disclosed** in the `LeadPacket` and were not back-filled. Identifying the managing principal is a required follow-up before any outreach.

---

## 4. Products & Services

- **Detailed descriptions:** As an SBIC, 1st Source Capital Corporation deploys debt (and historically equity) capital into small businesses. The SBIC directory lists its strategy as **Direct Lending**. Entity-level product detail beyond the direct-lending strategy is **not disclosed** in the `LeadPacket`.
- **Pricing model:** SBIC vehicles typically earn interest income on direct-lending positions plus management economics. Entity-level fee/economics detail is **not disclosed**.
- **Competitive differentiators:** The scarce, regulated **SBA SBIC license** itself; access to SBA-guaranteed leverage. A long operating history is plausible given the 1983 fund vintage but the company's formation date is an unresolved enrichment gap and is not asserted here.

---

## 5. Market Analysis

- **Industry size and trends:** SBICs are SBA-licensed private investment funds (venture, private equity, private credit) that provide debt and/or equity financing to small businesses, using SBA government-guaranteed leverage. The SBIC program has seen renewed federal emphasis (e.g., 2023–2024 SBA program expansions). SBIC licenses are scarce and tightly regulated under 13 CFR Part 107.
- **Growth drivers and barriers:** *Drivers* — SBA leverage amplifies investable capital; program tailwinds from recent SBA modernization. *Barriers* — the regulatory regime, capital minimums (Regulatory Capital ≥ $5M for post-1996 licensees), and SBA approval of any control change.
- **Competitive landscape:** The SBIC peer set is the broader SBA SBIC directory (hundreds of licensed SBICs nationally). 1st Source Capital is a **small SBIC** ($2.85M fund size per the `LeadPacket`) that is **not currently making new investments** — i.e., effectively in a wind-down / hold posture rather than actively deploying.

---

## 6. Customers & Revenue Model

- **Customer segments:** Portfolio companies are small businesses receiving direct-lending capital. Specific portfolio detail is **not disclosed** in the `LeadPacket`.
- **Retention rates:** Not applicable / not disclosed.
- **Recurring vs one-time revenue breakdown:** Not disclosed at the entity level. SBIC economics are typically a mix of recurring interest/management income and realized gains — but unconfirmed here, so the rubric recurring-revenue line was scored "insufficient data — not awarded".
- **Top customer concentration:** Not disclosed. With a small fund size, portfolio concentration is plausibly high, but this is not confirmed and was not scored as a ❌.

---

## 7. Financial Analysis

### Historical performance (last 3–5 years)

| Year | Revenue | EBITDA | EBITDA margin | YoY rev growth |
|------|---------|--------|---------------|----------------|
| 2022 | Not disclosed | Not disclosed | Not disclosed | — |
| 2023 | Not disclosed | Not disclosed | Not disclosed | — |
| 2024 | Not disclosed | Not disclosed | Not disclosed | — |
| 2025 (YTD / annualized) | Not disclosed | Not disclosed | Not disclosed | — |

The standalone SBIC management entity's financial statements are **not disclosed** in the `LeadPacket`. **No figures were estimated** — per skill rule 1, missing beats guessed.

### Growth trajectory
Not computable — no revenue or EBITDA series is available for the SBIC entity. Fund-level (informational only): vintage 1983, $2.85M fund size, $283,740 average investment, **not currently making new investments**.

### Estimated valuation
- **Implied multiple at ask:** Not computable — **off-market target, no asking price**.
- **Comparable multiples for industry:** SBIC GP / management-company transactions are typically priced on AUM, license value, and carried-interest economics rather than an EBITDA multiple; no public comp set was assembled for this dry run.
- **Fair entry range:** Not estimable without an SBA-approval-contingent negotiation and disclosed entity financials.

---

## 8. SWOT Analysis

| Strengths | Weaknesses |
|---|---|
| Holds a scarce SBA SBIC license in **good standing** | SBIC entity standalone financials, FTE, formation date, and ownership detail **not disclosed** |
| Established direct-lending SBIC vehicle (fund vintage 1983 per the `LeadPacket`) | **Not currently making new investments** — effectively in a hold/wind-down posture |

| Opportunities | Threats |
|---|---|
| A licensed SBIC charter is a strategic asset; could be reactivated for new deployment | **Not for sale** — no indication of seller intent |
| SBA program tailwinds (recent SBIC program modernization / expansion) | **SBA prior approval** of change of control is a mandatory, timeline-extending closing condition |

---

## 9. Risk Factors

- **Industry-specific risks:** SBIC operations are tightly regulated under 13 CFR Part 107; SBA leverage carries compliance and reporting obligations; a dormant ("not making new investments") SBIC may face license-maintenance questions.
- **Financial risks:** Standalone entity financials are **undisclosed** — EBITDA, revenue, growth, and portfolio/LP concentration could not be evaluated. Small fund size ($2.85M) implies limited standalone earnings power.
- **Operational risks:** GP managing principal not identified — key-person and continuity risk is unassessed. The ownership structure is undisclosed; a carve-out, if applicable, would require disentangling shared services.
- **Regulatory / legal:** **SBA prior approval of any change of control is mandatory** — the deal cannot close without it. SBIC licensees must maintain regulatory capital and good standing.
- **Deal-specific conditions:**
  1. **SBA approval of the change of control is a condition precedent to closing** — build it into the LOI, purchase agreement, and timeline.
  2. Confirm the SBIC license number and current good-standing status directly with the SBA (license number is an open enrichment gap).
  3. Identify the GP managing principal and confirm transition intent.
  4. Obtain standalone SBIC-entity financials before assigning any valuation.
  5. Establish the ownership structure and whether the owner is a willing seller — this is an off-market target with no indication it is available.

---

## 10. Outlook & Growth Opportunities

- **Expansion potential:** A licensed SBIC currently *not* deploying could be reactivated for new direct-lending or equity investment, drawing SBA-guaranteed leverage — the license is the platform.
- **Operational upside:** Reactivating dormant SBA leverage capacity; installing an active investment team; modernizing the portfolio-management process.
- **Strategic opportunities:** For an acquirer seeking SBIC status, buying an existing good-standing license can be faster than a de novo SBA application — provided SBA approves the change of control.
- **100-day plan sketch (if pursued):**
  1. Confirm SBA license number and good standing directly with the SBA; open the change-of-control approval dialogue early.
  2. Establish the ownership structure and whether the owner is a willing seller; if so, obtain standalone SBIC-entity financials.
  3. Identify and meet the GP managing principal.
  4. Model valuation on AUM / license / carry economics once entity financials are in hand.
  5. Structure the LOI with SBA change-of-control approval as an explicit condition precedent.

---

## 11. Appendix

### A. Data sources

- SBA SBIC Directory (https://www.sba.gov/funding-programs/investment-capital/sbic-directory) — source of the SBIC listing, fund vintage (1983), fund size ($2.85M), average investment ($283,740), direct-lending strategy, "not making new investments" status, and IR contact, as resolved into the off-market `LeadPacket`. Government open-data source.
- `output/reports/name-1st-source-capital-south-bend-in/lead-packet.json` — the off-market `LeadPacket` for this candidate; the **sole input** to this report.

> No external sources (SEC EDGAR, CB Insights, Wikipedia, press, etc.) were used: this report is scored strictly from the `LeadPacket` per `scoring_integration.md` §3. Any value not in the packet appears here as "not disclosed".

### B. Assumptions used for estimates

- **None.** No financial, headcount, valuation, or formation-date values were estimated or back-filled. Every undisclosed field is left blank or marked "not disclosed" per skill rule 1 (missing > guessed) and `scoring_integration.md` §3 (a gap stays a gap).

### C. Calculations for estimated fields

- **None** — no `(est.)` values appear in this report.

### D. Documents reviewed

- `output/reports/name-1st-source-capital-south-bend-in/lead-packet.json` — the off-market `LeadPacket` for this candidate; source of the SBIC license status, GP economics, contact, government fact, and enrichment gaps. This is the only document reviewed.

### E. Open questions for the seller / broker

- Confirm the SBA SBIC license number and current good-standing status directly with the SBA (license number not published by the directory — open gap).
- Identify the GP managing principal (directory POC is investor relations, not the deal principal).
- Obtain the SBIC management entity's standalone financials (revenue, EBITDA, FTE).
- Confirm the ownership structure and whether the owner is a willing seller — this is an off-market target.
- Confirm the company's formation/incorporation date — an open enrichment gap in the `LeadPacket`.

---

### s10 dry-run notes (build-loop bookkeeping)

- `eval_mode`: **sbic** (Class 2 → SBIC mode per `scoring_integration.md` §2).
- `score_is_informational`: **true** — the 20/100 score does not gate the SBIC decision.
- `buybox_gate`: **pass** — derived from `sbic_license_status: Good Standing` per §4.
- "No asking price" handling: **graceful** — Buy Box line 5 marked ⚠️ "insufficient data"; rubric valuation line scored **0 "insufficient data — not awarded"**. The run did not crash, abort, or drop the candidate. (`scoring_integration.md` §3.2 satisfied.)
- Formation date handling: **gap passed through** — `formation_date`/`years_in_business` are `null` in the packet; Buy Box line 3 and the rubric years-in-business line scored **0 "insufficient data — not awarded"**, never back-filled (`scoring_integration.md` §3, BLOCKING-s10-1 fix).
- `sbic_gp_economics` treated as **informational fund-level data** — not mapped onto any Buy Box financial criterion or the years-in-business line (§3.1).
- SBA prior-approval-of-change-of-control fact: **present** (dedicated section above + Risk Factors).
- `scoring_notes`: ["no asking price (off-market) — valuation line not awarded, not a failure"; "SBIC GP economics informational only — not mapped to EBITDA/valuation/years-in-business"; "formation date is an enrichment gap — years-in-business not awarded, not back-filled"; "SBIC license Good Standing → buybox_gate pass"; "score informational only (SBIC mode)"].
